/**
 * @file database.c
 *
 * @brief This source file was generated by cantools version 42.0.3 Fri Jul 31 12:48:06 2026.
 *
 * @copyright Copyright (c) 2018-2019 Erik Moqvist
 *
 * @par License
 * The MIT License (MIT)
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use, copy,
 * modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
 * BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
 * ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

#include <string.h>

#include "database.h"

static inline uint8_t pack_left_shift_u8(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_left_shift_u16(
    uint16_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_right_shift_u16(
    uint16_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value >> shift) & mask);
}

static inline uint16_t unpack_left_shift_u16(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint16_t)((uint16_t)(value & mask) << shift);
}

static inline uint8_t unpack_right_shift_u8(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value & mask) >> shift);
}

static inline uint16_t unpack_right_shift_u16(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint16_t)((uint16_t)(value & mask) >> shift);
}

int database_base0_pack(
    uint8_t *dst_p,
    const struct database_base0_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u16(src_p->warning_counter, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(src_p->warning_counter, 8u, 0xffu);
    dst_p[2] |= pack_left_shift_u16(src_p->last_error, 0u, 0xffu);
    dst_p[3] |= pack_right_shift_u16(src_p->last_error, 8u, 0xffu);
    dst_p[4] |= pack_left_shift_u8(src_p->rev_lim_act, 0u, 0x01u);
    dst_p[4] |= pack_left_shift_u8(src_p->main_relay_act, 1u, 0x02u);
    dst_p[4] |= pack_left_shift_u8(src_p->fuel_pump_act, 2u, 0x04u);
    dst_p[4] |= pack_left_shift_u8(src_p->cel_act, 3u, 0x08u);
    dst_p[4] |= pack_left_shift_u8(src_p->ego_heat_act, 4u, 0x10u);
    dst_p[4] |= pack_left_shift_u8(src_p->lambda_protect_act, 5u, 0x20u);
    dst_p[4] |= pack_left_shift_u8(src_p->fan, 6u, 0x40u);
    dst_p[4] |= pack_left_shift_u8(src_p->fan2, 7u, 0x80u);
    dst_p[5] |= pack_left_shift_u8(src_p->current_gear, 0u, 0xffu);
    dst_p[6] |= pack_left_shift_u16(src_p->distance_traveled, 0u, 0xffu);
    dst_p[7] |= pack_right_shift_u16(src_p->distance_traveled, 8u, 0xffu);

    return (8);
}

int database_base0_unpack(
    struct database_base0_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->warning_counter = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    dst_p->warning_counter |= unpack_left_shift_u16(src_p[1], 8u, 0xffu);
    dst_p->last_error = unpack_right_shift_u16(src_p[2], 0u, 0xffu);
    dst_p->last_error |= unpack_left_shift_u16(src_p[3], 8u, 0xffu);
    dst_p->rev_lim_act = unpack_right_shift_u8(src_p[4], 0u, 0x01u);
    dst_p->main_relay_act = unpack_right_shift_u8(src_p[4], 1u, 0x02u);
    dst_p->fuel_pump_act = unpack_right_shift_u8(src_p[4], 2u, 0x04u);
    dst_p->cel_act = unpack_right_shift_u8(src_p[4], 3u, 0x08u);
    dst_p->ego_heat_act = unpack_right_shift_u8(src_p[4], 4u, 0x10u);
    dst_p->lambda_protect_act = unpack_right_shift_u8(src_p[4], 5u, 0x20u);
    dst_p->fan = unpack_right_shift_u8(src_p[4], 6u, 0x40u);
    dst_p->fan2 = unpack_right_shift_u8(src_p[4], 7u, 0x80u);
    dst_p->current_gear = unpack_right_shift_u8(src_p[5], 0u, 0xffu);
    dst_p->distance_traveled = unpack_right_shift_u16(src_p[6], 0u, 0xffu);
    dst_p->distance_traveled |= unpack_left_shift_u16(src_p[7], 8u, 0xffu);

    return (0);
}

int database_base0_init(struct database_base0_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct database_base0_t));

    return 0;
}

uint16_t database_base0_warning_counter_encode(float value)
{
    return (uint16_t)(value);
}

float database_base0_warning_counter_decode(uint16_t value)
{
    return ((float)value);
}

bool database_base0_warning_counter_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

bool database_base0_warning_counter_is_in_phys_range(float value)
{
    (void)value;

    return (true);
}

uint16_t database_base0_last_error_encode(float value)
{
    return (uint16_t)(value);
}

float database_base0_last_error_decode(uint16_t value)
{
    return ((float)value);
}

bool database_base0_last_error_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

bool database_base0_last_error_is_in_phys_range(float value)
{
    (void)value;

    return (true);
}

uint8_t database_base0_rev_lim_act_encode(float value)
{
    return (uint8_t)(value);
}

float database_base0_rev_lim_act_decode(uint8_t value)
{
    return ((float)value);
}

bool database_base0_rev_lim_act_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool database_base0_rev_lim_act_is_in_phys_range(float value)
{
    (void)value;

    return (true);
}

uint8_t database_base0_main_relay_act_encode(float value)
{
    return (uint8_t)(value);
}

float database_base0_main_relay_act_decode(uint8_t value)
{
    return ((float)value);
}

bool database_base0_main_relay_act_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool database_base0_main_relay_act_is_in_phys_range(float value)
{
    (void)value;

    return (true);
}

uint8_t database_base0_fuel_pump_act_encode(float value)
{
    return (uint8_t)(value);
}

float database_base0_fuel_pump_act_decode(uint8_t value)
{
    return ((float)value);
}

bool database_base0_fuel_pump_act_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool database_base0_fuel_pump_act_is_in_phys_range(float value)
{
    (void)value;

    return (true);
}

uint8_t database_base0_cel_act_encode(float value)
{
    return (uint8_t)(value);
}

float database_base0_cel_act_decode(uint8_t value)
{
    return ((float)value);
}

bool database_base0_cel_act_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool database_base0_cel_act_is_in_phys_range(float value)
{
    (void)value;

    return (true);
}

uint8_t database_base0_ego_heat_act_encode(float value)
{
    return (uint8_t)(value);
}

float database_base0_ego_heat_act_decode(uint8_t value)
{
    return ((float)value);
}

bool database_base0_ego_heat_act_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool database_base0_ego_heat_act_is_in_phys_range(float value)
{
    (void)value;

    return (true);
}

uint8_t database_base0_lambda_protect_act_encode(float value)
{
    return (uint8_t)(value);
}

float database_base0_lambda_protect_act_decode(uint8_t value)
{
    return ((float)value);
}

bool database_base0_lambda_protect_act_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool database_base0_lambda_protect_act_is_in_phys_range(float value)
{
    (void)value;

    return (true);
}

uint8_t database_base0_fan_encode(float value)
{
    return (uint8_t)(value);
}

float database_base0_fan_decode(uint8_t value)
{
    return ((float)value);
}

bool database_base0_fan_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool database_base0_fan_is_in_phys_range(float value)
{
    (void)value;

    return (true);
}

uint8_t database_base0_fan2_encode(float value)
{
    return (uint8_t)(value);
}

float database_base0_fan2_decode(uint8_t value)
{
    return ((float)value);
}

bool database_base0_fan2_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool database_base0_fan2_is_in_phys_range(float value)
{
    (void)value;

    return (true);
}

uint8_t database_base0_current_gear_encode(float value)
{
    return (uint8_t)(value);
}

float database_base0_current_gear_decode(uint8_t value)
{
    return ((float)value);
}

bool database_base0_current_gear_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

bool database_base0_current_gear_is_in_phys_range(float value)
{
    (void)value;

    return (true);
}

uint16_t database_base0_distance_traveled_encode(float value)
{
    return (uint16_t)(value / 0.1f);
}

float database_base0_distance_traveled_decode(uint16_t value)
{
    return ((float)value * 0.1f);
}

bool database_base0_distance_traveled_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

bool database_base0_distance_traveled_is_in_phys_range(float value)
{
    return ((value >= 0.0f) && (value <= 6553.5f));
}

int database_base1_pack(
    uint8_t *dst_p,
    const struct database_base1_t *src_p,
    size_t size)
{
    uint16_t ignition_timing;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u16(src_p->rpm, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(src_p->rpm, 8u, 0xffu);
    ignition_timing = (uint16_t)src_p->ignition_timing;
    dst_p[2] |= pack_left_shift_u16(ignition_timing, 0u, 0xffu);
    dst_p[3] |= pack_right_shift_u16(ignition_timing, 8u, 0xffu);
    dst_p[4] |= pack_left_shift_u8(src_p->inj_duty, 0u, 0xffu);
    dst_p[5] |= pack_left_shift_u8(src_p->ign_duty, 0u, 0xffu);
    dst_p[6] |= pack_left_shift_u8(src_p->vehicle_speed, 0u, 0xffu);
    dst_p[7] |= pack_left_shift_u8(src_p->flex_pct, 0u, 0xffu);

    return (8);
}

int database_base1_unpack(
    struct database_base1_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint16_t ignition_timing;

    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->rpm = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    dst_p->rpm |= unpack_left_shift_u16(src_p[1], 8u, 0xffu);
    ignition_timing = unpack_right_shift_u16(src_p[2], 0u, 0xffu);
    ignition_timing |= unpack_left_shift_u16(src_p[3], 8u, 0xffu);
    dst_p->ignition_timing = (int16_t)ignition_timing;
    dst_p->inj_duty = unpack_right_shift_u8(src_p[4], 0u, 0xffu);
    dst_p->ign_duty = unpack_right_shift_u8(src_p[5], 0u, 0xffu);
    dst_p->vehicle_speed = unpack_right_shift_u8(src_p[6], 0u, 0xffu);
    dst_p->flex_pct = unpack_right_shift_u8(src_p[7], 0u, 0xffu);

    return (0);
}

int database_base1_init(struct database_base1_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct database_base1_t));

    return 0;
}

uint16_t database_base1_rpm_encode(float value)
{
    return (uint16_t)(value);
}

float database_base1_rpm_decode(uint16_t value)
{
    return ((float)value);
}

bool database_base1_rpm_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

bool database_base1_rpm_is_in_phys_range(float value)
{
    (void)value;

    return (true);
}

int16_t database_base1_ignition_timing_encode(float value)
{
    return (int16_t)(value / 0.02f);
}

float database_base1_ignition_timing_decode(int16_t value)
{
    return ((float)value * 0.02f);
}

bool database_base1_ignition_timing_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

bool database_base1_ignition_timing_is_in_phys_range(float value)
{
    (void)value;

    return (true);
}

uint8_t database_base1_inj_duty_encode(float value)
{
    return (uint8_t)(value / 0.5f);
}

float database_base1_inj_duty_decode(uint8_t value)
{
    return ((float)value * 0.5f);
}

bool database_base1_inj_duty_is_in_range(uint8_t value)
{
    return (value <= 200u);
}

bool database_base1_inj_duty_is_in_phys_range(float value)
{
    return ((value >= 0.0f) && (value <= 100.0f));
}

uint8_t database_base1_ign_duty_encode(float value)
{
    return (uint8_t)(value / 0.5f);
}

float database_base1_ign_duty_decode(uint8_t value)
{
    return ((float)value * 0.5f);
}

bool database_base1_ign_duty_is_in_range(uint8_t value)
{
    return (value <= 200u);
}

bool database_base1_ign_duty_is_in_phys_range(float value)
{
    return ((value >= 0.0f) && (value <= 100.0f));
}

uint8_t database_base1_vehicle_speed_encode(float value)
{
    return (uint8_t)(value);
}

float database_base1_vehicle_speed_decode(uint8_t value)
{
    return ((float)value);
}

bool database_base1_vehicle_speed_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

bool database_base1_vehicle_speed_is_in_phys_range(float value)
{
    return ((value >= 0.0f) && (value <= 255.0f));
}

uint8_t database_base1_flex_pct_encode(float value)
{
    return (uint8_t)(value);
}

float database_base1_flex_pct_decode(uint8_t value)
{
    return ((float)value);
}

bool database_base1_flex_pct_is_in_range(uint8_t value)
{
    return (value <= 100u);
}

bool database_base1_flex_pct_is_in_phys_range(float value)
{
    return ((value >= 0.0f) && (value <= 100.0f));
}

int database_base2_pack(
    uint8_t *dst_p,
    const struct database_base2_t *src_p,
    size_t size)
{
    uint16_t pps;
    uint16_t tps1;
    uint16_t tps2;
    uint16_t wastegate;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    pps = (uint16_t)src_p->pps;
    dst_p[0] |= pack_left_shift_u16(pps, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(pps, 8u, 0xffu);
    tps1 = (uint16_t)src_p->tps1;
    dst_p[2] |= pack_left_shift_u16(tps1, 0u, 0xffu);
    dst_p[3] |= pack_right_shift_u16(tps1, 8u, 0xffu);
    tps2 = (uint16_t)src_p->tps2;
    dst_p[4] |= pack_left_shift_u16(tps2, 0u, 0xffu);
    dst_p[5] |= pack_right_shift_u16(tps2, 8u, 0xffu);
    wastegate = (uint16_t)src_p->wastegate;
    dst_p[6] |= pack_left_shift_u16(wastegate, 0u, 0xffu);
    dst_p[7] |= pack_right_shift_u16(wastegate, 8u, 0xffu);

    return (8);
}

int database_base2_unpack(
    struct database_base2_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint16_t pps;
    uint16_t tps1;
    uint16_t tps2;
    uint16_t wastegate;

    if (size < 8u) {
        return (-EINVAL);
    }

    pps = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    pps |= unpack_left_shift_u16(src_p[1], 8u, 0xffu);
    dst_p->pps = (int16_t)pps;
    tps1 = unpack_right_shift_u16(src_p[2], 0u, 0xffu);
    tps1 |= unpack_left_shift_u16(src_p[3], 8u, 0xffu);
    dst_p->tps1 = (int16_t)tps1;
    tps2 = unpack_right_shift_u16(src_p[4], 0u, 0xffu);
    tps2 |= unpack_left_shift_u16(src_p[5], 8u, 0xffu);
    dst_p->tps2 = (int16_t)tps2;
    wastegate = unpack_right_shift_u16(src_p[6], 0u, 0xffu);
    wastegate |= unpack_left_shift_u16(src_p[7], 8u, 0xffu);
    dst_p->wastegate = (int16_t)wastegate;

    return (0);
}

int database_base2_init(struct database_base2_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct database_base2_t));

    return 0;
}

int16_t database_base2_pps_encode(float value)
{
    return (int16_t)(value / 0.01f);
}

float database_base2_pps_decode(int16_t value)
{
    return ((float)value * 0.01f);
}

bool database_base2_pps_is_in_range(int16_t value)
{
    return ((value >= 0) && (value <= 10000));
}

bool database_base2_pps_is_in_phys_range(float value)
{
    return ((value >= 0.0f) && (value <= 100.0f));
}

int16_t database_base2_tps1_encode(float value)
{
    return (int16_t)(value / 0.01f);
}

float database_base2_tps1_decode(int16_t value)
{
    return ((float)value * 0.01f);
}

bool database_base2_tps1_is_in_range(int16_t value)
{
    return ((value >= 0) && (value <= 10000));
}

bool database_base2_tps1_is_in_phys_range(float value)
{
    return ((value >= 0.0f) && (value <= 100.0f));
}

int16_t database_base2_tps2_encode(float value)
{
    return (int16_t)(value / 0.01f);
}

float database_base2_tps2_decode(int16_t value)
{
    return ((float)value * 0.01f);
}

bool database_base2_tps2_is_in_range(int16_t value)
{
    return ((value >= 0) && (value <= 10000));
}

bool database_base2_tps2_is_in_phys_range(float value)
{
    return ((value >= 0.0f) && (value <= 100.0f));
}

int16_t database_base2_wastegate_encode(float value)
{
    return (int16_t)(value / 0.01f);
}

float database_base2_wastegate_decode(int16_t value)
{
    return ((float)value * 0.01f);
}

bool database_base2_wastegate_is_in_range(int16_t value)
{
    return ((value >= 0) && (value <= 10000));
}

bool database_base2_wastegate_is_in_phys_range(float value)
{
    return ((value >= 0.0f) && (value <= 100.0f));
}

int database_base3_pack(
    uint8_t *dst_p,
    const struct database_base3_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u16(src_p->map, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(src_p->map, 8u, 0xffu);
    dst_p[2] |= pack_left_shift_u8(src_p->coolant_temp, 0u, 0xffu);
    dst_p[3] |= pack_left_shift_u8(src_p->intake_temp, 0u, 0xffu);
    dst_p[4] |= pack_left_shift_u8(src_p->aux1_temp, 0u, 0xffu);
    dst_p[5] |= pack_left_shift_u8(src_p->aux2_temp, 0u, 0xffu);
    dst_p[6] |= pack_left_shift_u8(src_p->mcu_temp, 0u, 0xffu);
    dst_p[7] |= pack_left_shift_u8(src_p->fuel_level, 0u, 0xffu);

    return (8);
}

int database_base3_unpack(
    struct database_base3_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->map = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    dst_p->map |= unpack_left_shift_u16(src_p[1], 8u, 0xffu);
    dst_p->coolant_temp = unpack_right_shift_u8(src_p[2], 0u, 0xffu);
    dst_p->intake_temp = unpack_right_shift_u8(src_p[3], 0u, 0xffu);
    dst_p->aux1_temp = unpack_right_shift_u8(src_p[4], 0u, 0xffu);
    dst_p->aux2_temp = unpack_right_shift_u8(src_p[5], 0u, 0xffu);
    dst_p->mcu_temp = unpack_right_shift_u8(src_p[6], 0u, 0xffu);
    dst_p->fuel_level = unpack_right_shift_u8(src_p[7], 0u, 0xffu);

    return (0);
}

int database_base3_init(struct database_base3_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct database_base3_t));

    return 0;
}

uint16_t database_base3_map_encode(float value)
{
    return (uint16_t)(value / 0.03333333f);
}

float database_base3_map_decode(uint16_t value)
{
    return ((float)value * 0.03333333f);
}

bool database_base3_map_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

bool database_base3_map_is_in_phys_range(float value)
{
    (void)value;

    return (true);
}

uint8_t database_base3_coolant_temp_encode(float value)
{
    return (uint8_t)(value - -40.0f);
}

float database_base3_coolant_temp_decode(uint8_t value)
{
    return ((float)value + -40.0f);
}

bool database_base3_coolant_temp_is_in_range(uint8_t value)
{
    return (value <= 240u);
}

bool database_base3_coolant_temp_is_in_phys_range(float value)
{
    return ((value >= -40.0f) && (value <= 200.0f));
}

uint8_t database_base3_intake_temp_encode(float value)
{
    return (uint8_t)(value - -40.0f);
}

float database_base3_intake_temp_decode(uint8_t value)
{
    return ((float)value + -40.0f);
}

bool database_base3_intake_temp_is_in_range(uint8_t value)
{
    return (value <= 240u);
}

bool database_base3_intake_temp_is_in_phys_range(float value)
{
    return ((value >= -40.0f) && (value <= 200.0f));
}

uint8_t database_base3_aux1_temp_encode(float value)
{
    return (uint8_t)(value - -40.0f);
}

float database_base3_aux1_temp_decode(uint8_t value)
{
    return ((float)value + -40.0f);
}

bool database_base3_aux1_temp_is_in_range(uint8_t value)
{
    return (value <= 240u);
}

bool database_base3_aux1_temp_is_in_phys_range(float value)
{
    return ((value >= -40.0f) && (value <= 200.0f));
}

uint8_t database_base3_aux2_temp_encode(float value)
{
    return (uint8_t)(value - -40.0f);
}

float database_base3_aux2_temp_decode(uint8_t value)
{
    return ((float)value + -40.0f);
}

bool database_base3_aux2_temp_is_in_range(uint8_t value)
{
    return (value <= 240u);
}

bool database_base3_aux2_temp_is_in_phys_range(float value)
{
    return ((value >= -40.0f) && (value <= 200.0f));
}

uint8_t database_base3_mcu_temp_encode(float value)
{
    return (uint8_t)(value - -40.0f);
}

float database_base3_mcu_temp_decode(uint8_t value)
{
    return ((float)value + -40.0f);
}

bool database_base3_mcu_temp_is_in_range(uint8_t value)
{
    return (value <= 140u);
}

bool database_base3_mcu_temp_is_in_phys_range(float value)
{
    return ((value >= -40.0f) && (value <= 100.0f));
}

uint8_t database_base3_fuel_level_encode(float value)
{
    return (uint8_t)(value / 0.5f);
}

float database_base3_fuel_level_decode(uint8_t value)
{
    return ((float)value * 0.5f);
}

bool database_base3_fuel_level_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

bool database_base3_fuel_level_is_in_phys_range(float value)
{
    (void)value;

    return (true);
}

int database_base4_pack(
    uint8_t *dst_p,
    const struct database_base4_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[2] |= pack_left_shift_u16(src_p->oil_press, 0u, 0xffu);
    dst_p[3] |= pack_right_shift_u16(src_p->oil_press, 8u, 0xffu);
    dst_p[4] |= pack_left_shift_u8(src_p->oil_temperature, 0u, 0xffu);
    dst_p[5] |= pack_left_shift_u8(src_p->fuel_temperature, 0u, 0xffu);
    dst_p[6] |= pack_left_shift_u16(src_p->batt_volt, 0u, 0xffu);
    dst_p[7] |= pack_right_shift_u16(src_p->batt_volt, 8u, 0xffu);

    return (8);
}

int database_base4_unpack(
    struct database_base4_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->oil_press = unpack_right_shift_u16(src_p[2], 0u, 0xffu);
    dst_p->oil_press |= unpack_left_shift_u16(src_p[3], 8u, 0xffu);
    dst_p->oil_temperature = unpack_right_shift_u8(src_p[4], 0u, 0xffu);
    dst_p->fuel_temperature = unpack_right_shift_u8(src_p[5], 0u, 0xffu);
    dst_p->batt_volt = unpack_right_shift_u16(src_p[6], 0u, 0xffu);
    dst_p->batt_volt |= unpack_left_shift_u16(src_p[7], 8u, 0xffu);

    return (0);
}

int database_base4_init(struct database_base4_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct database_base4_t));

    return 0;
}

uint16_t database_base4_oil_press_encode(float value)
{
    return (uint16_t)(value / 0.03333333f);
}

float database_base4_oil_press_decode(uint16_t value)
{
    return ((float)value * 0.03333333f);
}

bool database_base4_oil_press_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

bool database_base4_oil_press_is_in_phys_range(float value)
{
    (void)value;

    return (true);
}

uint8_t database_base4_oil_temperature_encode(float value)
{
    return (uint8_t)(value - -40.0f);
}

float database_base4_oil_temperature_decode(uint8_t value)
{
    return ((float)value + -40.0f);
}

bool database_base4_oil_temperature_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

bool database_base4_oil_temperature_is_in_phys_range(float value)
{
    return ((value >= -40.0f) && (value <= 215.0f));
}

uint8_t database_base4_fuel_temperature_encode(float value)
{
    return (uint8_t)(value - -40.0f);
}

float database_base4_fuel_temperature_decode(uint8_t value)
{
    return ((float)value + -40.0f);
}

bool database_base4_fuel_temperature_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

bool database_base4_fuel_temperature_is_in_phys_range(float value)
{
    return ((value >= -40.0f) && (value <= 215.0f));
}

uint16_t database_base4_batt_volt_encode(float value)
{
    return (uint16_t)(value / 0.001f);
}

float database_base4_batt_volt_decode(uint16_t value)
{
    return ((float)value * 0.001f);
}

bool database_base4_batt_volt_is_in_range(uint16_t value)
{
    return (value <= 25000u);
}

bool database_base4_batt_volt_is_in_phys_range(float value)
{
    return ((value >= 0.0f) && (value <= 25.0f));
}

int database_base5_pack(
    uint8_t *dst_p,
    const struct database_base5_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u16(src_p->cyl_am, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(src_p->cyl_am, 8u, 0xffu);
    dst_p[2] |= pack_left_shift_u16(src_p->est_maf, 0u, 0xffu);
    dst_p[3] |= pack_right_shift_u16(src_p->est_maf, 8u, 0xffu);
    dst_p[4] |= pack_left_shift_u16(src_p->inj_pw, 0u, 0xffu);
    dst_p[5] |= pack_right_shift_u16(src_p->inj_pw, 8u, 0xffu);
    dst_p[6] |= pack_left_shift_u16(src_p->knock_ct, 0u, 0xffu);
    dst_p[7] |= pack_right_shift_u16(src_p->knock_ct, 8u, 0xffu);

    return (8);
}

int database_base5_unpack(
    struct database_base5_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->cyl_am = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    dst_p->cyl_am |= unpack_left_shift_u16(src_p[1], 8u, 0xffu);
    dst_p->est_maf = unpack_right_shift_u16(src_p[2], 0u, 0xffu);
    dst_p->est_maf |= unpack_left_shift_u16(src_p[3], 8u, 0xffu);
    dst_p->inj_pw = unpack_right_shift_u16(src_p[4], 0u, 0xffu);
    dst_p->inj_pw |= unpack_left_shift_u16(src_p[5], 8u, 0xffu);
    dst_p->knock_ct = unpack_right_shift_u16(src_p[6], 0u, 0xffu);
    dst_p->knock_ct |= unpack_left_shift_u16(src_p[7], 8u, 0xffu);

    return (0);
}

int database_base5_init(struct database_base5_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct database_base5_t));

    return 0;
}

uint16_t database_base5_cyl_am_encode(float value)
{
    return (uint16_t)(value);
}

float database_base5_cyl_am_decode(uint16_t value)
{
    return ((float)value);
}

bool database_base5_cyl_am_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

bool database_base5_cyl_am_is_in_phys_range(float value)
{
    (void)value;

    return (true);
}

uint16_t database_base5_est_maf_encode(float value)
{
    return (uint16_t)(value / 0.01f);
}

float database_base5_est_maf_decode(uint16_t value)
{
    return ((float)value * 0.01f);
}

bool database_base5_est_maf_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

bool database_base5_est_maf_is_in_phys_range(float value)
{
    (void)value;

    return (true);
}

uint16_t database_base5_inj_pw_encode(float value)
{
    return (uint16_t)(value / 0.003333333f);
}

float database_base5_inj_pw_decode(uint16_t value)
{
    return ((float)value * 0.003333333f);
}

bool database_base5_inj_pw_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

bool database_base5_inj_pw_is_in_phys_range(float value)
{
    (void)value;

    return (true);
}

uint16_t database_base5_knock_ct_encode(float value)
{
    return (uint16_t)(value);
}

float database_base5_knock_ct_decode(uint16_t value)
{
    return ((float)value);
}

bool database_base5_knock_ct_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

bool database_base5_knock_ct_is_in_phys_range(float value)
{
    (void)value;

    return (true);
}

int database_base6_pack(
    uint8_t *dst_p,
    const struct database_base6_t *src_p,
    size_t size)
{
    uint16_t fuel_trim1;
    uint16_t fuel_trim2;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u16(src_p->fuel_used, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(src_p->fuel_used, 8u, 0xffu);
    dst_p[2] |= pack_left_shift_u16(src_p->fuel_flow, 0u, 0xffu);
    dst_p[3] |= pack_right_shift_u16(src_p->fuel_flow, 8u, 0xffu);
    fuel_trim1 = (uint16_t)src_p->fuel_trim1;
    dst_p[4] |= pack_left_shift_u16(fuel_trim1, 0u, 0xffu);
    dst_p[5] |= pack_right_shift_u16(fuel_trim1, 8u, 0xffu);
    fuel_trim2 = (uint16_t)src_p->fuel_trim2;
    dst_p[6] |= pack_left_shift_u16(fuel_trim2, 0u, 0xffu);
    dst_p[7] |= pack_right_shift_u16(fuel_trim2, 8u, 0xffu);

    return (8);
}

int database_base6_unpack(
    struct database_base6_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint16_t fuel_trim1;
    uint16_t fuel_trim2;

    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->fuel_used = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    dst_p->fuel_used |= unpack_left_shift_u16(src_p[1], 8u, 0xffu);
    dst_p->fuel_flow = unpack_right_shift_u16(src_p[2], 0u, 0xffu);
    dst_p->fuel_flow |= unpack_left_shift_u16(src_p[3], 8u, 0xffu);
    fuel_trim1 = unpack_right_shift_u16(src_p[4], 0u, 0xffu);
    fuel_trim1 |= unpack_left_shift_u16(src_p[5], 8u, 0xffu);
    dst_p->fuel_trim1 = (int16_t)fuel_trim1;
    fuel_trim2 = unpack_right_shift_u16(src_p[6], 0u, 0xffu);
    fuel_trim2 |= unpack_left_shift_u16(src_p[7], 8u, 0xffu);
    dst_p->fuel_trim2 = (int16_t)fuel_trim2;

    return (0);
}

int database_base6_init(struct database_base6_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct database_base6_t));

    return 0;
}

uint16_t database_base6_fuel_used_encode(float value)
{
    return (uint16_t)(value);
}

float database_base6_fuel_used_decode(uint16_t value)
{
    return ((float)value);
}

bool database_base6_fuel_used_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

bool database_base6_fuel_used_is_in_phys_range(float value)
{
    (void)value;

    return (true);
}

uint16_t database_base6_fuel_flow_encode(float value)
{
    return (uint16_t)(value / 0.005f);
}

float database_base6_fuel_flow_decode(uint16_t value)
{
    return ((float)value * 0.005f);
}

bool database_base6_fuel_flow_is_in_range(uint16_t value)
{
    return (value <= 65400u);
}

bool database_base6_fuel_flow_is_in_phys_range(float value)
{
    return ((value >= 0.0f) && (value <= 327.0f));
}

int16_t database_base6_fuel_trim1_encode(float value)
{
    return (int16_t)(value / 0.01f);
}

float database_base6_fuel_trim1_decode(int16_t value)
{
    return ((float)value * 0.01f);
}

bool database_base6_fuel_trim1_is_in_range(int16_t value)
{
    return ((value >= -5000) && (value <= 5000));
}

bool database_base6_fuel_trim1_is_in_phys_range(float value)
{
    return ((value >= -50.0f) && (value <= 50.0f));
}

int16_t database_base6_fuel_trim2_encode(float value)
{
    return (int16_t)(value / 0.01f);
}

float database_base6_fuel_trim2_decode(int16_t value)
{
    return ((float)value * 0.01f);
}

bool database_base6_fuel_trim2_is_in_range(int16_t value)
{
    return ((value >= -5000) && (value <= 5000));
}

bool database_base6_fuel_trim2_is_in_phys_range(float value)
{
    return ((value >= -50.0f) && (value <= 50.0f));
}

int database_base7_pack(
    uint8_t *dst_p,
    const struct database_base7_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u16(src_p->lam1, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(src_p->lam1, 8u, 0xffu);
    dst_p[2] |= pack_left_shift_u16(src_p->lam2, 0u, 0xffu);
    dst_p[3] |= pack_right_shift_u16(src_p->lam2, 8u, 0xffu);
    dst_p[4] |= pack_left_shift_u16(src_p->fp_low, 0u, 0xffu);
    dst_p[5] |= pack_right_shift_u16(src_p->fp_low, 8u, 0xffu);
    dst_p[6] |= pack_left_shift_u16(src_p->fp_high, 0u, 0xffu);
    dst_p[7] |= pack_right_shift_u16(src_p->fp_high, 8u, 0xffu);

    return (8);
}

int database_base7_unpack(
    struct database_base7_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->lam1 = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    dst_p->lam1 |= unpack_left_shift_u16(src_p[1], 8u, 0xffu);
    dst_p->lam2 = unpack_right_shift_u16(src_p[2], 0u, 0xffu);
    dst_p->lam2 |= unpack_left_shift_u16(src_p[3], 8u, 0xffu);
    dst_p->fp_low = unpack_right_shift_u16(src_p[4], 0u, 0xffu);
    dst_p->fp_low |= unpack_left_shift_u16(src_p[5], 8u, 0xffu);
    dst_p->fp_high = unpack_right_shift_u16(src_p[6], 0u, 0xffu);
    dst_p->fp_high |= unpack_left_shift_u16(src_p[7], 8u, 0xffu);

    return (0);
}

int database_base7_init(struct database_base7_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct database_base7_t));

    return 0;
}

uint16_t database_base7_lam1_encode(float value)
{
    return (uint16_t)(value / 0.0001f);
}

float database_base7_lam1_decode(uint16_t value)
{
    return ((float)value * 0.0001f);
}

bool database_base7_lam1_is_in_range(uint16_t value)
{
    return (value <= 20000u);
}

bool database_base7_lam1_is_in_phys_range(float value)
{
    return ((value >= 0.0f) && (value <= 2.0f));
}

uint16_t database_base7_lam2_encode(float value)
{
    return (uint16_t)(value / 0.0001f);
}

float database_base7_lam2_decode(uint16_t value)
{
    return ((float)value * 0.0001f);
}

bool database_base7_lam2_is_in_range(uint16_t value)
{
    return (value <= 20000u);
}

bool database_base7_lam2_is_in_phys_range(float value)
{
    return ((value >= 0.0f) && (value <= 2.0f));
}

uint16_t database_base7_fp_low_encode(float value)
{
    return (uint16_t)(value / 0.03333333f);
}

float database_base7_fp_low_decode(uint16_t value)
{
    return ((float)value * 0.03333333f);
}

bool database_base7_fp_low_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

bool database_base7_fp_low_is_in_phys_range(float value)
{
    (void)value;

    return (true);
}

uint16_t database_base7_fp_high_encode(float value)
{
    return (uint16_t)(value / 0.1f);
}

float database_base7_fp_high_decode(uint16_t value)
{
    return ((float)value * 0.1f);
}

bool database_base7_fp_high_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

bool database_base7_fp_high_is_in_phys_range(float value)
{
    (void)value;

    return (true);
}

int database_base8_pack(
    uint8_t *dst_p,
    const struct database_base8_t *src_p,
    size_t size)
{
    uint8_t cam1_e;
    uint8_t cam1_etar;
    uint8_t cam1_i;
    uint8_t cam1_itar;
    uint8_t cam2_e;
    uint8_t cam2_etar;
    uint8_t cam2_i;
    uint8_t cam2_itar;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    cam1_i = (uint8_t)src_p->cam1_i;
    dst_p[0] |= pack_left_shift_u8(cam1_i, 0u, 0xffu);
    cam1_itar = (uint8_t)src_p->cam1_itar;
    dst_p[1] |= pack_left_shift_u8(cam1_itar, 0u, 0xffu);
    cam1_e = (uint8_t)src_p->cam1_e;
    dst_p[2] |= pack_left_shift_u8(cam1_e, 0u, 0xffu);
    cam1_etar = (uint8_t)src_p->cam1_etar;
    dst_p[3] |= pack_left_shift_u8(cam1_etar, 0u, 0xffu);
    cam2_i = (uint8_t)src_p->cam2_i;
    dst_p[4] |= pack_left_shift_u8(cam2_i, 0u, 0xffu);
    cam2_itar = (uint8_t)src_p->cam2_itar;
    dst_p[5] |= pack_left_shift_u8(cam2_itar, 0u, 0xffu);
    cam2_e = (uint8_t)src_p->cam2_e;
    dst_p[6] |= pack_left_shift_u8(cam2_e, 0u, 0xffu);
    cam2_etar = (uint8_t)src_p->cam2_etar;
    dst_p[7] |= pack_left_shift_u8(cam2_etar, 0u, 0xffu);

    return (8);
}

int database_base8_unpack(
    struct database_base8_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint8_t cam1_e;
    uint8_t cam1_etar;
    uint8_t cam1_i;
    uint8_t cam1_itar;
    uint8_t cam2_e;
    uint8_t cam2_etar;
    uint8_t cam2_i;
    uint8_t cam2_itar;

    if (size < 8u) {
        return (-EINVAL);
    }

    cam1_i = unpack_right_shift_u8(src_p[0], 0u, 0xffu);
    dst_p->cam1_i = (int8_t)cam1_i;
    cam1_itar = unpack_right_shift_u8(src_p[1], 0u, 0xffu);
    dst_p->cam1_itar = (int8_t)cam1_itar;
    cam1_e = unpack_right_shift_u8(src_p[2], 0u, 0xffu);
    dst_p->cam1_e = (int8_t)cam1_e;
    cam1_etar = unpack_right_shift_u8(src_p[3], 0u, 0xffu);
    dst_p->cam1_etar = (int8_t)cam1_etar;
    cam2_i = unpack_right_shift_u8(src_p[4], 0u, 0xffu);
    dst_p->cam2_i = (int8_t)cam2_i;
    cam2_itar = unpack_right_shift_u8(src_p[5], 0u, 0xffu);
    dst_p->cam2_itar = (int8_t)cam2_itar;
    cam2_e = unpack_right_shift_u8(src_p[6], 0u, 0xffu);
    dst_p->cam2_e = (int8_t)cam2_e;
    cam2_etar = unpack_right_shift_u8(src_p[7], 0u, 0xffu);
    dst_p->cam2_etar = (int8_t)cam2_etar;

    return (0);
}

int database_base8_init(struct database_base8_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct database_base8_t));

    return 0;
}

int8_t database_base8_cam1_i_encode(float value)
{
    return (int8_t)(value);
}

float database_base8_cam1_i_decode(int8_t value)
{
    return ((float)value);
}

bool database_base8_cam1_i_is_in_range(int8_t value)
{
    return ((value >= -100) && (value <= 100));
}

bool database_base8_cam1_i_is_in_phys_range(float value)
{
    return ((value >= -100.0f) && (value <= 100.0f));
}

int8_t database_base8_cam1_itar_encode(float value)
{
    return (int8_t)(value);
}

float database_base8_cam1_itar_decode(int8_t value)
{
    return ((float)value);
}

bool database_base8_cam1_itar_is_in_range(int8_t value)
{
    return ((value >= -100) && (value <= 100));
}

bool database_base8_cam1_itar_is_in_phys_range(float value)
{
    return ((value >= -100.0f) && (value <= 100.0f));
}

int8_t database_base8_cam1_e_encode(float value)
{
    return (int8_t)(value);
}

float database_base8_cam1_e_decode(int8_t value)
{
    return ((float)value);
}

bool database_base8_cam1_e_is_in_range(int8_t value)
{
    return ((value >= -100) && (value <= 100));
}

bool database_base8_cam1_e_is_in_phys_range(float value)
{
    return ((value >= -100.0f) && (value <= 100.0f));
}

int8_t database_base8_cam1_etar_encode(float value)
{
    return (int8_t)(value);
}

float database_base8_cam1_etar_decode(int8_t value)
{
    return ((float)value);
}

bool database_base8_cam1_etar_is_in_range(int8_t value)
{
    return ((value >= -100) && (value <= 100));
}

bool database_base8_cam1_etar_is_in_phys_range(float value)
{
    return ((value >= -100.0f) && (value <= 100.0f));
}

int8_t database_base8_cam2_i_encode(float value)
{
    return (int8_t)(value);
}

float database_base8_cam2_i_decode(int8_t value)
{
    return ((float)value);
}

bool database_base8_cam2_i_is_in_range(int8_t value)
{
    return ((value >= -100) && (value <= 100));
}

bool database_base8_cam2_i_is_in_phys_range(float value)
{
    return ((value >= -100.0f) && (value <= 100.0f));
}

int8_t database_base8_cam2_itar_encode(float value)
{
    return (int8_t)(value);
}

float database_base8_cam2_itar_decode(int8_t value)
{
    return ((float)value);
}

bool database_base8_cam2_itar_is_in_range(int8_t value)
{
    return ((value >= -100) && (value <= 100));
}

bool database_base8_cam2_itar_is_in_phys_range(float value)
{
    return ((value >= -100.0f) && (value <= 100.0f));
}

int8_t database_base8_cam2_e_encode(float value)
{
    return (int8_t)(value);
}

float database_base8_cam2_e_decode(int8_t value)
{
    return ((float)value);
}

bool database_base8_cam2_e_is_in_range(int8_t value)
{
    return ((value >= -100) && (value <= 100));
}

bool database_base8_cam2_e_is_in_phys_range(float value)
{
    return ((value >= -100.0f) && (value <= 100.0f));
}

int8_t database_base8_cam2_etar_encode(float value)
{
    return (int8_t)(value);
}

float database_base8_cam2_etar_decode(int8_t value)
{
    return ((float)value);
}

bool database_base8_cam2_etar_is_in_range(int8_t value)
{
    return ((value >= -100) && (value <= 100));
}

bool database_base8_cam2_etar_is_in_phys_range(float value)
{
    return ((value >= -100.0f) && (value <= 100.0f));
}

int database_base9_pack(
    uint8_t *dst_p,
    const struct database_base9_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u8(src_p->egt1, 0u, 0xffu);
    dst_p[1] |= pack_left_shift_u8(src_p->egt2, 0u, 0xffu);
    dst_p[2] |= pack_left_shift_u8(src_p->egt3, 0u, 0xffu);
    dst_p[3] |= pack_left_shift_u8(src_p->egt4, 0u, 0xffu);
    dst_p[4] |= pack_left_shift_u8(src_p->egt5, 0u, 0xffu);
    dst_p[5] |= pack_left_shift_u8(src_p->egt6, 0u, 0xffu);
    dst_p[6] |= pack_left_shift_u8(src_p->egt7, 0u, 0xffu);
    dst_p[7] |= pack_left_shift_u8(src_p->egt8, 0u, 0xffu);

    return (8);
}

int database_base9_unpack(
    struct database_base9_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->egt1 = unpack_right_shift_u8(src_p[0], 0u, 0xffu);
    dst_p->egt2 = unpack_right_shift_u8(src_p[1], 0u, 0xffu);
    dst_p->egt3 = unpack_right_shift_u8(src_p[2], 0u, 0xffu);
    dst_p->egt4 = unpack_right_shift_u8(src_p[3], 0u, 0xffu);
    dst_p->egt5 = unpack_right_shift_u8(src_p[4], 0u, 0xffu);
    dst_p->egt6 = unpack_right_shift_u8(src_p[5], 0u, 0xffu);
    dst_p->egt7 = unpack_right_shift_u8(src_p[6], 0u, 0xffu);
    dst_p->egt8 = unpack_right_shift_u8(src_p[7], 0u, 0xffu);

    return (0);
}

int database_base9_init(struct database_base9_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct database_base9_t));

    return 0;
}

uint8_t database_base9_egt1_encode(float value)
{
    return (uint8_t)(value / 5.0f);
}

float database_base9_egt1_decode(uint8_t value)
{
    return ((float)value * 5.0f);
}

bool database_base9_egt1_is_in_range(uint8_t value)
{
    return (value <= 250u);
}

bool database_base9_egt1_is_in_phys_range(float value)
{
    return ((value >= 0.0f) && (value <= 1250.0f));
}

uint8_t database_base9_egt2_encode(float value)
{
    return (uint8_t)(value / 5.0f);
}

float database_base9_egt2_decode(uint8_t value)
{
    return ((float)value * 5.0f);
}

bool database_base9_egt2_is_in_range(uint8_t value)
{
    return (value <= 250u);
}

bool database_base9_egt2_is_in_phys_range(float value)
{
    return ((value >= 0.0f) && (value <= 1250.0f));
}

uint8_t database_base9_egt3_encode(float value)
{
    return (uint8_t)(value / 5.0f);
}

float database_base9_egt3_decode(uint8_t value)
{
    return ((float)value * 5.0f);
}

bool database_base9_egt3_is_in_range(uint8_t value)
{
    return (value <= 250u);
}

bool database_base9_egt3_is_in_phys_range(float value)
{
    return ((value >= 0.0f) && (value <= 1250.0f));
}

uint8_t database_base9_egt4_encode(float value)
{
    return (uint8_t)(value / 5.0f);
}

float database_base9_egt4_decode(uint8_t value)
{
    return ((float)value * 5.0f);
}

bool database_base9_egt4_is_in_range(uint8_t value)
{
    return (value <= 250u);
}

bool database_base9_egt4_is_in_phys_range(float value)
{
    return ((value >= 0.0f) && (value <= 1250.0f));
}

uint8_t database_base9_egt5_encode(float value)
{
    return (uint8_t)(value / 5.0f);
}

float database_base9_egt5_decode(uint8_t value)
{
    return ((float)value * 5.0f);
}

bool database_base9_egt5_is_in_range(uint8_t value)
{
    return (value <= 250u);
}

bool database_base9_egt5_is_in_phys_range(float value)
{
    return ((value >= 0.0f) && (value <= 1250.0f));
}

uint8_t database_base9_egt6_encode(float value)
{
    return (uint8_t)(value / 5.0f);
}

float database_base9_egt6_decode(uint8_t value)
{
    return ((float)value * 5.0f);
}

bool database_base9_egt6_is_in_range(uint8_t value)
{
    return (value <= 250u);
}

bool database_base9_egt6_is_in_phys_range(float value)
{
    return ((value >= 0.0f) && (value <= 1250.0f));
}

uint8_t database_base9_egt7_encode(float value)
{
    return (uint8_t)(value / 5.0f);
}

float database_base9_egt7_decode(uint8_t value)
{
    return ((float)value * 5.0f);
}

bool database_base9_egt7_is_in_range(uint8_t value)
{
    return (value <= 250u);
}

bool database_base9_egt7_is_in_phys_range(float value)
{
    return ((value >= 0.0f) && (value <= 1250.0f));
}

uint8_t database_base9_egt8_encode(float value)
{
    return (uint8_t)(value / 5.0f);
}

float database_base9_egt8_decode(uint8_t value)
{
    return ((float)value * 5.0f);
}

bool database_base9_egt8_is_in_range(uint8_t value)
{
    return (value <= 250u);
}

bool database_base9_egt8_is_in_phys_range(float value)
{
    return ((value >= 0.0f) && (value <= 1250.0f));
}

int database_base10_pack(
    uint8_t *dst_p,
    const struct database_base10_t *src_p,
    size_t size)
{
    uint8_t knock0;
    uint8_t knock1;
    uint8_t knock2;
    uint8_t knock3;
    uint8_t knock4;
    uint8_t knock5;
    uint8_t knock6;
    uint8_t knock7;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    knock0 = (uint8_t)src_p->knock0;
    dst_p[0] |= pack_left_shift_u8(knock0, 0u, 0xffu);
    knock1 = (uint8_t)src_p->knock1;
    dst_p[1] |= pack_left_shift_u8(knock1, 0u, 0xffu);
    knock2 = (uint8_t)src_p->knock2;
    dst_p[2] |= pack_left_shift_u8(knock2, 0u, 0xffu);
    knock3 = (uint8_t)src_p->knock3;
    dst_p[3] |= pack_left_shift_u8(knock3, 0u, 0xffu);
    knock4 = (uint8_t)src_p->knock4;
    dst_p[4] |= pack_left_shift_u8(knock4, 0u, 0xffu);
    knock5 = (uint8_t)src_p->knock5;
    dst_p[5] |= pack_left_shift_u8(knock5, 0u, 0xffu);
    knock6 = (uint8_t)src_p->knock6;
    dst_p[6] |= pack_left_shift_u8(knock6, 0u, 0xffu);
    knock7 = (uint8_t)src_p->knock7;
    dst_p[7] |= pack_left_shift_u8(knock7, 0u, 0xffu);

    return (8);
}

int database_base10_unpack(
    struct database_base10_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint8_t knock0;
    uint8_t knock1;
    uint8_t knock2;
    uint8_t knock3;
    uint8_t knock4;
    uint8_t knock5;
    uint8_t knock6;
    uint8_t knock7;

    if (size < 8u) {
        return (-EINVAL);
    }

    knock0 = unpack_right_shift_u8(src_p[0], 0u, 0xffu);
    dst_p->knock0 = (int8_t)knock0;
    knock1 = unpack_right_shift_u8(src_p[1], 0u, 0xffu);
    dst_p->knock1 = (int8_t)knock1;
    knock2 = unpack_right_shift_u8(src_p[2], 0u, 0xffu);
    dst_p->knock2 = (int8_t)knock2;
    knock3 = unpack_right_shift_u8(src_p[3], 0u, 0xffu);
    dst_p->knock3 = (int8_t)knock3;
    knock4 = unpack_right_shift_u8(src_p[4], 0u, 0xffu);
    dst_p->knock4 = (int8_t)knock4;
    knock5 = unpack_right_shift_u8(src_p[5], 0u, 0xffu);
    dst_p->knock5 = (int8_t)knock5;
    knock6 = unpack_right_shift_u8(src_p[6], 0u, 0xffu);
    dst_p->knock6 = (int8_t)knock6;
    knock7 = unpack_right_shift_u8(src_p[7], 0u, 0xffu);
    dst_p->knock7 = (int8_t)knock7;

    return (0);
}

int database_base10_init(struct database_base10_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct database_base10_t));

    return 0;
}

int8_t database_base10_knock0_encode(float value)
{
    return (int8_t)(value);
}

float database_base10_knock0_decode(int8_t value)
{
    return ((float)value);
}

bool database_base10_knock0_is_in_range(int8_t value)
{
    return ((value >= -60) && (value <= 10));
}

bool database_base10_knock0_is_in_phys_range(float value)
{
    return ((value >= -60.0f) && (value <= 10.0f));
}

int8_t database_base10_knock1_encode(float value)
{
    return (int8_t)(value);
}

float database_base10_knock1_decode(int8_t value)
{
    return ((float)value);
}

bool database_base10_knock1_is_in_range(int8_t value)
{
    return ((value >= -60) && (value <= 10));
}

bool database_base10_knock1_is_in_phys_range(float value)
{
    return ((value >= -60.0f) && (value <= 10.0f));
}

int8_t database_base10_knock2_encode(float value)
{
    return (int8_t)(value);
}

float database_base10_knock2_decode(int8_t value)
{
    return ((float)value);
}

bool database_base10_knock2_is_in_range(int8_t value)
{
    return ((value >= -60) && (value <= 10));
}

bool database_base10_knock2_is_in_phys_range(float value)
{
    return ((value >= -60.0f) && (value <= 10.0f));
}

int8_t database_base10_knock3_encode(float value)
{
    return (int8_t)(value);
}

float database_base10_knock3_decode(int8_t value)
{
    return ((float)value);
}

bool database_base10_knock3_is_in_range(int8_t value)
{
    return ((value >= -60) && (value <= 10));
}

bool database_base10_knock3_is_in_phys_range(float value)
{
    return ((value >= -60.0f) && (value <= 10.0f));
}

int8_t database_base10_knock4_encode(float value)
{
    return (int8_t)(value);
}

float database_base10_knock4_decode(int8_t value)
{
    return ((float)value);
}

bool database_base10_knock4_is_in_range(int8_t value)
{
    return ((value >= -60) && (value <= 10));
}

bool database_base10_knock4_is_in_phys_range(float value)
{
    return ((value >= -60.0f) && (value <= 10.0f));
}

int8_t database_base10_knock5_encode(float value)
{
    return (int8_t)(value);
}

float database_base10_knock5_decode(int8_t value)
{
    return ((float)value);
}

bool database_base10_knock5_is_in_range(int8_t value)
{
    return ((value >= -60) && (value <= 10));
}

bool database_base10_knock5_is_in_phys_range(float value)
{
    return ((value >= -60.0f) && (value <= 10.0f));
}

int8_t database_base10_knock6_encode(float value)
{
    return (int8_t)(value);
}

float database_base10_knock6_decode(int8_t value)
{
    return ((float)value);
}

bool database_base10_knock6_is_in_range(int8_t value)
{
    return ((value >= -60) && (value <= 10));
}

bool database_base10_knock6_is_in_phys_range(float value)
{
    return ((value >= -60.0f) && (value <= 10.0f));
}

int8_t database_base10_knock7_encode(float value)
{
    return (int8_t)(value);
}

float database_base10_knock7_decode(int8_t value)
{
    return ((float)value);
}

bool database_base10_knock7_is_in_range(int8_t value)
{
    return ((value >= -60) && (value <= 10));
}

bool database_base10_knock7_is_in_phys_range(float value)
{
    return ((value >= -60.0f) && (value <= 10.0f));
}

int database_base11_pack(
    uint8_t *dst_p,
    const struct database_base11_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u8(src_p->brake_pedal, 0u, 0x01u);

    return (8);
}

int database_base11_unpack(
    struct database_base11_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->brake_pedal = unpack_right_shift_u8(src_p[0], 0u, 0x01u);

    return (0);
}

int database_base11_init(struct database_base11_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct database_base11_t));

    return 0;
}

uint8_t database_base11_brake_pedal_encode(float value)
{
    return (uint8_t)(value);
}

float database_base11_brake_pedal_decode(uint8_t value)
{
    return ((float)value);
}

bool database_base11_brake_pedal_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool database_base11_brake_pedal_is_in_phys_range(float value)
{
    (void)value;

    return (true);
}
