/**
 * @file database.h
 *
 * @brief This header file was generated by cantools version 42.0.3 Fri Jul 31 12:48:06 2026.
 *
 * @copyright Copyright (c) 2018-2019 Erik Moqvist
 *
 * @par License
 * The MIT License (MIT)
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use, copy,
 * modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
 * BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
 * ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

#ifndef DATABASE_H
#define DATABASE_H

#ifdef __cplusplus
extern "C" {
#endif

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

#ifndef EINVAL
#    define EINVAL 22
#endif

/* Frame ids. */
#define DATABASE_BASE0_FRAME_ID (0x200u)
#define DATABASE_BASE1_FRAME_ID (0x201u)
#define DATABASE_BASE2_FRAME_ID (0x202u)
#define DATABASE_BASE3_FRAME_ID (0x203u)
#define DATABASE_BASE4_FRAME_ID (0x204u)
#define DATABASE_BASE5_FRAME_ID (0x205u)
#define DATABASE_BASE6_FRAME_ID (0x206u)
#define DATABASE_BASE7_FRAME_ID (0x207u)
#define DATABASE_BASE8_FRAME_ID (0x208u)
#define DATABASE_BASE9_FRAME_ID (0x209u)
#define DATABASE_BASE10_FRAME_ID (0x20au)
#define DATABASE_BASE11_FRAME_ID (0x20bu)

/* Frame lengths in bytes. */
#define DATABASE_BASE0_LENGTH (8u)
#define DATABASE_BASE1_LENGTH (8u)
#define DATABASE_BASE2_LENGTH (8u)
#define DATABASE_BASE3_LENGTH (8u)
#define DATABASE_BASE4_LENGTH (8u)
#define DATABASE_BASE5_LENGTH (8u)
#define DATABASE_BASE6_LENGTH (8u)
#define DATABASE_BASE7_LENGTH (8u)
#define DATABASE_BASE8_LENGTH (8u)
#define DATABASE_BASE9_LENGTH (8u)
#define DATABASE_BASE10_LENGTH (8u)
#define DATABASE_BASE11_LENGTH (8u)

/* Extended or standard frame types. */
#define DATABASE_BASE0_IS_EXTENDED (0)
#define DATABASE_BASE1_IS_EXTENDED (0)
#define DATABASE_BASE2_IS_EXTENDED (0)
#define DATABASE_BASE3_IS_EXTENDED (0)
#define DATABASE_BASE4_IS_EXTENDED (0)
#define DATABASE_BASE5_IS_EXTENDED (0)
#define DATABASE_BASE6_IS_EXTENDED (0)
#define DATABASE_BASE7_IS_EXTENDED (0)
#define DATABASE_BASE8_IS_EXTENDED (0)
#define DATABASE_BASE9_IS_EXTENDED (0)
#define DATABASE_BASE10_IS_EXTENDED (0)
#define DATABASE_BASE11_IS_EXTENDED (0)

/* Frame cycle times in milliseconds. */


/* Signal choices. */


/* Frame Names. */
#define DATABASE_BASE0_NAME "BASE0"
#define DATABASE_BASE1_NAME "BASE1"
#define DATABASE_BASE2_NAME "BASE2"
#define DATABASE_BASE3_NAME "BASE3"
#define DATABASE_BASE4_NAME "BASE4"
#define DATABASE_BASE5_NAME "BASE5"
#define DATABASE_BASE6_NAME "BASE6"
#define DATABASE_BASE7_NAME "BASE7"
#define DATABASE_BASE8_NAME "BASE8"
#define DATABASE_BASE9_NAME "BASE9"
#define DATABASE_BASE10_NAME "BASE10"
#define DATABASE_BASE11_NAME "BASE11"

/* Signal Names. */
#define DATABASE_BASE0_WARNING_COUNTER_NAME "WarningCounter"
#define DATABASE_BASE0_LAST_ERROR_NAME "LastError"
#define DATABASE_BASE0_REV_LIM_ACT_NAME "RevLimAct"
#define DATABASE_BASE0_MAIN_RELAY_ACT_NAME "MainRelayAct"
#define DATABASE_BASE0_FUEL_PUMP_ACT_NAME "FuelPumpAct"
#define DATABASE_BASE0_CEL_ACT_NAME "CELAct"
#define DATABASE_BASE0_EGO_HEAT_ACT_NAME "EGOHeatAct"
#define DATABASE_BASE0_LAMBDA_PROTECT_ACT_NAME "LambdaProtectAct"
#define DATABASE_BASE0_FAN_NAME "Fan"
#define DATABASE_BASE0_FAN2_NAME "Fan2"
#define DATABASE_BASE0_CURRENT_GEAR_NAME "CurrentGear"
#define DATABASE_BASE0_DISTANCE_TRAVELED_NAME "DistanceTraveled"
#define DATABASE_BASE1_RPM_NAME "RPM"
#define DATABASE_BASE1_IGNITION_TIMING_NAME "IgnitionTiming"
#define DATABASE_BASE1_INJ_DUTY_NAME "InjDuty"
#define DATABASE_BASE1_IGN_DUTY_NAME "IgnDuty"
#define DATABASE_BASE1_VEHICLE_SPEED_NAME "VehicleSpeed"
#define DATABASE_BASE1_FLEX_PCT_NAME "FlexPct"
#define DATABASE_BASE2_PPS_NAME "PPS"
#define DATABASE_BASE2_TPS1_NAME "TPS1"
#define DATABASE_BASE2_TPS2_NAME "TPS2"
#define DATABASE_BASE2_WASTEGATE_NAME "Wastegate"
#define DATABASE_BASE3_MAP_NAME "MAP"
#define DATABASE_BASE3_COOLANT_TEMP_NAME "CoolantTemp"
#define DATABASE_BASE3_INTAKE_TEMP_NAME "IntakeTemp"
#define DATABASE_BASE3_AUX1_TEMP_NAME "AUX1Temp"
#define DATABASE_BASE3_AUX2_TEMP_NAME "AUX2Temp"
#define DATABASE_BASE3_MCU_TEMP_NAME "MCUTemp"
#define DATABASE_BASE3_FUEL_LEVEL_NAME "FuelLevel"
#define DATABASE_BASE4_OIL_PRESS_NAME "OilPress"
#define DATABASE_BASE4_OIL_TEMPERATURE_NAME "OilTemperature"
#define DATABASE_BASE4_FUEL_TEMPERATURE_NAME "FuelTemperature"
#define DATABASE_BASE4_BATT_VOLT_NAME "BattVolt"
#define DATABASE_BASE5_CYL_AM_NAME "CylAM"
#define DATABASE_BASE5_EST_MAF_NAME "EstMAF"
#define DATABASE_BASE5_INJ_PW_NAME "InjPW"
#define DATABASE_BASE5_KNOCK_CT_NAME "KnockCt"
#define DATABASE_BASE6_FUEL_USED_NAME "FuelUsed"
#define DATABASE_BASE6_FUEL_FLOW_NAME "FuelFlow"
#define DATABASE_BASE6_FUEL_TRIM1_NAME "FuelTrim1"
#define DATABASE_BASE6_FUEL_TRIM2_NAME "FuelTrim2"
#define DATABASE_BASE7_LAM1_NAME "Lam1"
#define DATABASE_BASE7_LAM2_NAME "Lam2"
#define DATABASE_BASE7_FP_LOW_NAME "FpLow"
#define DATABASE_BASE7_FP_HIGH_NAME "FpHigh"
#define DATABASE_BASE8_CAM1_I_NAME "Cam1I"
#define DATABASE_BASE8_CAM1_ITAR_NAME "Cam1Itar"
#define DATABASE_BASE8_CAM1_E_NAME "Cam1E"
#define DATABASE_BASE8_CAM1_ETAR_NAME "Cam1Etar"
#define DATABASE_BASE8_CAM2_I_NAME "Cam2I"
#define DATABASE_BASE8_CAM2_ITAR_NAME "Cam2Itar"
#define DATABASE_BASE8_CAM2_E_NAME "Cam2E"
#define DATABASE_BASE8_CAM2_ETAR_NAME "Cam2Etar"
#define DATABASE_BASE9_EGT1_NAME "Egt1"
#define DATABASE_BASE9_EGT2_NAME "Egt2"
#define DATABASE_BASE9_EGT3_NAME "Egt3"
#define DATABASE_BASE9_EGT4_NAME "Egt4"
#define DATABASE_BASE9_EGT5_NAME "Egt5"
#define DATABASE_BASE9_EGT6_NAME "Egt6"
#define DATABASE_BASE9_EGT7_NAME "Egt7"
#define DATABASE_BASE9_EGT8_NAME "Egt8"
#define DATABASE_BASE10_KNOCK0_NAME "knock0"
#define DATABASE_BASE10_KNOCK1_NAME "knock1"
#define DATABASE_BASE10_KNOCK2_NAME "knock2"
#define DATABASE_BASE10_KNOCK3_NAME "knock3"
#define DATABASE_BASE10_KNOCK4_NAME "knock4"
#define DATABASE_BASE10_KNOCK5_NAME "knock5"
#define DATABASE_BASE10_KNOCK6_NAME "knock6"
#define DATABASE_BASE10_KNOCK7_NAME "knock7"
#define DATABASE_BASE11_BRAKE_PEDAL_NAME "BrakePedal"

/**
 * Signals in message BASE0.
 *
 * All signal values are as on the CAN bus.
 */
struct database_base0_t {
    /**
     * Total warnings since ECU start time
     *
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    uint16_t warning_counter;

    /**
     * Last error code
     *
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    uint16_t last_error;

    /**
     * RPM Limiter Active
     *
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    uint8_t rev_lim_act;

    /**
     * Main Relay Active
     *
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    uint8_t main_relay_act;

    /**
     * Fuel Pump Output Active
     *
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    uint8_t fuel_pump_act;

    /**
     * Check Engine Light Active
     *
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    uint8_t cel_act;

    /**
     * EGO Heater Commanded On
     *
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    uint8_t ego_heat_act;

    /**
     * Lambda protection active (fault detected)
     *
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    uint8_t lambda_protect_act;

    /**
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    uint8_t fan;

    /**
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    uint8_t fan2;

    /**
     * Current detected gear. 0 means neutral, 1 means first, etc.
     *
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    uint8_t current_gear;

    /**
     * Distance traveled since reset
     *
     * Range: 0..65535 (0..6553.5 km)
     * Scale: 0.1
     * Offset: 0
     */
    uint16_t distance_traveled;
};

/**
 * Signals in message BASE1.
 *
 * All signal values are as on the CAN bus.
 */
struct database_base1_t {
    /**
     * Current RPM
     *
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    uint16_t rpm;

    /**
     * Current Ignition Timing. Positive is advance.
     *
     * Range: -
     * Scale: 0.02
     * Offset: 0
     */
    int16_t ignition_timing;

    /**
     * Injection Duty
     *
     * Range: 0..200 (0..100 %)
     * Scale: 0.5
     * Offset: 0
     */
    uint8_t inj_duty;

    /**
     * Ignition Duty
     *
     * Range: 0..200 (0..100 %)
     * Scale: 0.5
     * Offset: 0
     */
    uint8_t ign_duty;

    /**
     * Current Vehicle Speed
     *
     * Range: 0..255 (0..255 kph)
     * Scale: 1
     * Offset: 0
     */
    uint8_t vehicle_speed;

    /**
     * Ethanol percent
     *
     * Range: 0..100 (0..100 %)
     * Scale: 1
     * Offset: 0
     */
    uint8_t flex_pct;
};

/**
 * Signals in message BASE2.
 *
 * Throttle positions
 *
 * All signal values are as on the CAN bus.
 */
struct database_base2_t {
    /**
     * Current Accelerator Pedal Position
     *
     * Range: 0..10000 (0..100 %)
     * Scale: 0.01
     * Offset: 0
     */
    int16_t pps;

    /**
     * Throttle Body 1 Position
     *
     * Range: 0..10000 (0..100 %)
     * Scale: 0.01
     * Offset: 0
     */
    int16_t tps1;

    /**
     * Throttle Body 2 Position
     *
     * Range: 0..10000 (0..100 %)
     * Scale: 0.01
     * Offset: 0
     */
    int16_t tps2;

    /**
     * Wastegate actuator position
     *
     * Range: 0..10000 (0..100 %)
     * Scale: 0.01
     * Offset: 0
     */
    int16_t wastegate;
};

/**
 * Signals in message BASE3.
 *
 * All signal values are as on the CAN bus.
 */
struct database_base3_t {
    /**
     * Current MAP Reading
     *
     * Range: -
     * Scale: 0.03333333
     * Offset: 0
     */
    uint16_t map;

    /**
     * Current Coolant Temperature Reading
     *
     * Range: 0..240 (-40..200 deg C)
     * Scale: 1
     * Offset: -40
     */
    uint8_t coolant_temp;

    /**
     * Current Intake Air Temperature
     *
     * Range: 0..240 (-40..200 deg C)
     * Scale: 1
     * Offset: -40
     */
    uint8_t intake_temp;

    /**
     * Current Aux1 Temperature
     *
     * Range: 0..240 (-40..200 deg C)
     * Scale: 1
     * Offset: -40
     */
    uint8_t aux1_temp;

    /**
     * Current Aux2 Temperature
     *
     * Range: 0..240 (-40..200 deg C)
     * Scale: 1
     * Offset: -40
     */
    uint8_t aux2_temp;

    /**
     * Current MCU Temperature
     *
     * Range: 0..140 (-40..100 deg C)
     * Scale: 1
     * Offset: -40
     */
    uint8_t mcu_temp;

    /**
     * Current Fuel Level
     *
     * Range: -
     * Scale: 0.5
     * Offset: 0
     */
    uint8_t fuel_level;
};

/**
 * Signals in message BASE4.
 *
 * All signal values are as on the CAN bus.
 */
struct database_base4_t {
    /**
     * Current Oil Pressure Reading
     *
     * Range: -
     * Scale: 0.03333333
     * Offset: 0
     */
    uint16_t oil_press;

    /**
     * Range: 0..255 (-40..215 deg C)
     * Scale: 1
     * Offset: -40
     */
    uint8_t oil_temperature;

    /**
     * Range: 0..255 (-40..215 deg C)
     * Scale: 1
     * Offset: -40
     */
    uint8_t fuel_temperature;

    /**
     * Current Battery Voltage Reading
     *
     * Range: 0..25000 (0..25 mV)
     * Scale: 0.001
     * Offset: 0
     */
    uint16_t batt_volt;
};

/**
 * Signals in message BASE5.
 *
 * All signal values are as on the CAN bus.
 */
struct database_base5_t {
    /**
     * Current Estmated Cylinder Airmass
     *
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    uint16_t cyl_am;

    /**
     * Current Estimated Total Airflow
     *
     * Range: -
     * Scale: 0.01
     * Offset: 0
     */
    uint16_t est_maf;

    /**
     * Current Commanded Injector Pulsewidth
     *
     * Range: -
     * Scale: 0.003333333
     * Offset: 0
     */
    uint16_t inj_pw;

    /**
     * Knock detection counter
     *
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    uint16_t knock_ct;
};

/**
 * Signals in message BASE6.
 *
 * All signal values are as on the CAN bus.
 */
struct database_base6_t {
    /**
     * Total fuel consumed
     *
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    uint16_t fuel_used;

    /**
     * Fuel flow rate
     *
     * Range: 0..65400 (0..327 g/s)
     * Scale: 0.005
     * Offset: 0
     */
    uint16_t fuel_flow;

    /**
     * Fuel trim bank 1
     *
     * Range: -5000..5000 (-50..50 %)
     * Scale: 0.01
     * Offset: 0
     */
    int16_t fuel_trim1;

    /**
     * Fuel trim bank 2
     *
     * Range: -5000..5000 (-50..50 %)
     * Scale: 0.01
     * Offset: 0
     */
    int16_t fuel_trim2;
};

/**
 * Signals in message BASE7.
 *
 * Fueling
 *
 * All signal values are as on the CAN bus.
 */
struct database_base7_t {
    /**
     * Lambda sensor 1
     *
     * Range: 0..20000 (0..2 lambda)
     * Scale: 0.0001
     * Offset: 0
     */
    uint16_t lam1;

    /**
     * Lambda sensor 2
     *
     * Range: 0..20000 (0..2 lambda)
     * Scale: 0.0001
     * Offset: 0
     */
    uint16_t lam2;

    /**
     * Fuel pressure - low sensor
     *
     * Range: -
     * Scale: 0.03333333
     * Offset: 0
     */
    uint16_t fp_low;

    /**
     * Fuel pressure - high (GDI) sensor
     *
     * Range: -
     * Scale: 0.1
     * Offset: 0
     */
    uint16_t fp_high;
};

/**
 * Signals in message BASE8.
 *
 * Cams
 *
 * All signal values are as on the CAN bus.
 */
struct database_base8_t {
    /**
     * Cam bank 1 intake actual
     *
     * Range: -100..100 (-100..100 deg)
     * Scale: 1
     * Offset: 0
     */
    int8_t cam1_i;

    /**
     * Cam bank 1 intake target
     *
     * Range: -100..100 (-100..100 deg)
     * Scale: 1
     * Offset: 0
     */
    int8_t cam1_itar;

    /**
     * Cam bank 1 exhaust actual
     *
     * Range: -100..100 (-100..100 deg)
     * Scale: 1
     * Offset: 0
     */
    int8_t cam1_e;

    /**
     * Cam bank 1 exhaust target
     *
     * Range: -100..100 (-100..100 deg)
     * Scale: 1
     * Offset: 0
     */
    int8_t cam1_etar;

    /**
     * Cam bank 2 intake actual
     *
     * Range: -100..100 (-100..100 deg)
     * Scale: 1
     * Offset: 0
     */
    int8_t cam2_i;

    /**
     * Cam bank 2 intake target
     *
     * Range: -100..100 (-100..100 deg)
     * Scale: 1
     * Offset: 0
     */
    int8_t cam2_itar;

    /**
     * Cam bank 2 exhaust actual
     *
     * Range: -100..100 (-100..100 deg)
     * Scale: 1
     * Offset: 0
     */
    int8_t cam2_e;

    /**
     * Cam bank 2 exhaust target
     *
     * Range: -100..100 (-100..100 deg)
     * Scale: 1
     * Offset: 0
     */
    int8_t cam2_etar;
};

/**
 * Signals in message BASE9.
 *
 * All signal values are as on the CAN bus.
 */
struct database_base9_t {
    /**
     * Range: 0..250 (0..1250 deg C)
     * Scale: 5
     * Offset: 0
     */
    uint8_t egt1;

    /**
     * Range: 0..250 (0..1250 deg C)
     * Scale: 5
     * Offset: 0
     */
    uint8_t egt2;

    /**
     * Range: 0..250 (0..1250 deg C)
     * Scale: 5
     * Offset: 0
     */
    uint8_t egt3;

    /**
     * Range: 0..250 (0..1250 deg C)
     * Scale: 5
     * Offset: 0
     */
    uint8_t egt4;

    /**
     * Range: 0..250 (0..1250 deg C)
     * Scale: 5
     * Offset: 0
     */
    uint8_t egt5;

    /**
     * Range: 0..250 (0..1250 deg C)
     * Scale: 5
     * Offset: 0
     */
    uint8_t egt6;

    /**
     * Range: 0..250 (0..1250 deg C)
     * Scale: 5
     * Offset: 0
     */
    uint8_t egt7;

    /**
     * Range: 0..250 (0..1250 deg C)
     * Scale: 5
     * Offset: 0
     */
    uint8_t egt8;
};

/**
 * Signals in message BASE10.
 *
 * All signal values are as on the CAN bus.
 */
struct database_base10_t {
    /**
     * Range: -60..10 (-60..10 db)
     * Scale: 1
     * Offset: 0
     */
    int8_t knock0;

    /**
     * Range: -60..10 (-60..10 db)
     * Scale: 1
     * Offset: 0
     */
    int8_t knock1;

    /**
     * Range: -60..10 (-60..10 db)
     * Scale: 1
     * Offset: 0
     */
    int8_t knock2;

    /**
     * Range: -60..10 (-60..10 db)
     * Scale: 1
     * Offset: 0
     */
    int8_t knock3;

    /**
     * Range: -60..10 (-60..10 db)
     * Scale: 1
     * Offset: 0
     */
    int8_t knock4;

    /**
     * Range: -60..10 (-60..10 db)
     * Scale: 1
     * Offset: 0
     */
    int8_t knock5;

    /**
     * Range: -60..10 (-60..10 db)
     * Scale: 1
     * Offset: 0
     */
    int8_t knock6;

    /**
     * Range: -60..10 (-60..10 db)
     * Scale: 1
     * Offset: 0
     */
    int8_t knock7;
};

/**
 * Signals in message BASE11.
 *
 * All signal values are as on the CAN bus.
 */
struct database_base11_t {
    /**
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    uint8_t brake_pedal;
};

/**
 * Pack message BASE0.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int database_base0_pack(
    uint8_t *dst_p,
    const struct database_base0_t *src_p,
    size_t size);

/**
 * Unpack message BASE0.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int database_base0_unpack(
    struct database_base0_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from BASE0.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int database_base0_init(struct database_base0_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t database_base0_warning_counter_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float database_base0_warning_counter_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool database_base0_warning_counter_is_in_range(uint16_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool database_base0_warning_counter_is_in_phys_range(float value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t database_base0_last_error_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float database_base0_last_error_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool database_base0_last_error_is_in_range(uint16_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool database_base0_last_error_is_in_phys_range(float value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t database_base0_rev_lim_act_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float database_base0_rev_lim_act_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool database_base0_rev_lim_act_is_in_range(uint8_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool database_base0_rev_lim_act_is_in_phys_range(float value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t database_base0_main_relay_act_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float database_base0_main_relay_act_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool database_base0_main_relay_act_is_in_range(uint8_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool database_base0_main_relay_act_is_in_phys_range(float value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t database_base0_fuel_pump_act_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float database_base0_fuel_pump_act_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool database_base0_fuel_pump_act_is_in_range(uint8_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool database_base0_fuel_pump_act_is_in_phys_range(float value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t database_base0_cel_act_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float database_base0_cel_act_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool database_base0_cel_act_is_in_range(uint8_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool database_base0_cel_act_is_in_phys_range(float value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t database_base0_ego_heat_act_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float database_base0_ego_heat_act_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool database_base0_ego_heat_act_is_in_range(uint8_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool database_base0_ego_heat_act_is_in_phys_range(float value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t database_base0_lambda_protect_act_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float database_base0_lambda_protect_act_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool database_base0_lambda_protect_act_is_in_range(uint8_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool database_base0_lambda_protect_act_is_in_phys_range(float value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t database_base0_fan_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float database_base0_fan_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool database_base0_fan_is_in_range(uint8_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool database_base0_fan_is_in_phys_range(float value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t database_base0_fan2_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float database_base0_fan2_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool database_base0_fan2_is_in_range(uint8_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool database_base0_fan2_is_in_phys_range(float value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t database_base0_current_gear_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float database_base0_current_gear_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool database_base0_current_gear_is_in_range(uint8_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool database_base0_current_gear_is_in_phys_range(float value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t database_base0_distance_traveled_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float database_base0_distance_traveled_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool database_base0_distance_traveled_is_in_range(uint16_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool database_base0_distance_traveled_is_in_phys_range(float value);

/**
 * Pack message BASE1.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int database_base1_pack(
    uint8_t *dst_p,
    const struct database_base1_t *src_p,
    size_t size);

/**
 * Unpack message BASE1.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int database_base1_unpack(
    struct database_base1_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from BASE1.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int database_base1_init(struct database_base1_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t database_base1_rpm_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float database_base1_rpm_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool database_base1_rpm_is_in_range(uint16_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool database_base1_rpm_is_in_phys_range(float value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
int16_t database_base1_ignition_timing_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float database_base1_ignition_timing_decode(int16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool database_base1_ignition_timing_is_in_range(int16_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool database_base1_ignition_timing_is_in_phys_range(float value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t database_base1_inj_duty_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float database_base1_inj_duty_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool database_base1_inj_duty_is_in_range(uint8_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool database_base1_inj_duty_is_in_phys_range(float value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t database_base1_ign_duty_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float database_base1_ign_duty_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool database_base1_ign_duty_is_in_range(uint8_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool database_base1_ign_duty_is_in_phys_range(float value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t database_base1_vehicle_speed_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float database_base1_vehicle_speed_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool database_base1_vehicle_speed_is_in_range(uint8_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool database_base1_vehicle_speed_is_in_phys_range(float value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t database_base1_flex_pct_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float database_base1_flex_pct_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool database_base1_flex_pct_is_in_range(uint8_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool database_base1_flex_pct_is_in_phys_range(float value);

/**
 * Pack message BASE2.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int database_base2_pack(
    uint8_t *dst_p,
    const struct database_base2_t *src_p,
    size_t size);

/**
 * Unpack message BASE2.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int database_base2_unpack(
    struct database_base2_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from BASE2.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int database_base2_init(struct database_base2_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
int16_t database_base2_pps_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float database_base2_pps_decode(int16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool database_base2_pps_is_in_range(int16_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool database_base2_pps_is_in_phys_range(float value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
int16_t database_base2_tps1_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float database_base2_tps1_decode(int16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool database_base2_tps1_is_in_range(int16_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool database_base2_tps1_is_in_phys_range(float value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
int16_t database_base2_tps2_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float database_base2_tps2_decode(int16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool database_base2_tps2_is_in_range(int16_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool database_base2_tps2_is_in_phys_range(float value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
int16_t database_base2_wastegate_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float database_base2_wastegate_decode(int16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool database_base2_wastegate_is_in_range(int16_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool database_base2_wastegate_is_in_phys_range(float value);

/**
 * Pack message BASE3.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int database_base3_pack(
    uint8_t *dst_p,
    const struct database_base3_t *src_p,
    size_t size);

/**
 * Unpack message BASE3.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int database_base3_unpack(
    struct database_base3_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from BASE3.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int database_base3_init(struct database_base3_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t database_base3_map_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float database_base3_map_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool database_base3_map_is_in_range(uint16_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool database_base3_map_is_in_phys_range(float value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t database_base3_coolant_temp_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float database_base3_coolant_temp_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool database_base3_coolant_temp_is_in_range(uint8_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool database_base3_coolant_temp_is_in_phys_range(float value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t database_base3_intake_temp_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float database_base3_intake_temp_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool database_base3_intake_temp_is_in_range(uint8_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool database_base3_intake_temp_is_in_phys_range(float value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t database_base3_aux1_temp_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float database_base3_aux1_temp_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool database_base3_aux1_temp_is_in_range(uint8_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool database_base3_aux1_temp_is_in_phys_range(float value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t database_base3_aux2_temp_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float database_base3_aux2_temp_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool database_base3_aux2_temp_is_in_range(uint8_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool database_base3_aux2_temp_is_in_phys_range(float value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t database_base3_mcu_temp_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float database_base3_mcu_temp_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool database_base3_mcu_temp_is_in_range(uint8_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool database_base3_mcu_temp_is_in_phys_range(float value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t database_base3_fuel_level_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float database_base3_fuel_level_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool database_base3_fuel_level_is_in_range(uint8_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool database_base3_fuel_level_is_in_phys_range(float value);

/**
 * Pack message BASE4.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int database_base4_pack(
    uint8_t *dst_p,
    const struct database_base4_t *src_p,
    size_t size);

/**
 * Unpack message BASE4.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int database_base4_unpack(
    struct database_base4_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from BASE4.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int database_base4_init(struct database_base4_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t database_base4_oil_press_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float database_base4_oil_press_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool database_base4_oil_press_is_in_range(uint16_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool database_base4_oil_press_is_in_phys_range(float value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t database_base4_oil_temperature_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float database_base4_oil_temperature_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool database_base4_oil_temperature_is_in_range(uint8_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool database_base4_oil_temperature_is_in_phys_range(float value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t database_base4_fuel_temperature_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float database_base4_fuel_temperature_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool database_base4_fuel_temperature_is_in_range(uint8_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool database_base4_fuel_temperature_is_in_phys_range(float value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t database_base4_batt_volt_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float database_base4_batt_volt_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool database_base4_batt_volt_is_in_range(uint16_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool database_base4_batt_volt_is_in_phys_range(float value);

/**
 * Pack message BASE5.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int database_base5_pack(
    uint8_t *dst_p,
    const struct database_base5_t *src_p,
    size_t size);

/**
 * Unpack message BASE5.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int database_base5_unpack(
    struct database_base5_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from BASE5.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int database_base5_init(struct database_base5_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t database_base5_cyl_am_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float database_base5_cyl_am_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool database_base5_cyl_am_is_in_range(uint16_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool database_base5_cyl_am_is_in_phys_range(float value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t database_base5_est_maf_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float database_base5_est_maf_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool database_base5_est_maf_is_in_range(uint16_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool database_base5_est_maf_is_in_phys_range(float value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t database_base5_inj_pw_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float database_base5_inj_pw_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool database_base5_inj_pw_is_in_range(uint16_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool database_base5_inj_pw_is_in_phys_range(float value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t database_base5_knock_ct_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float database_base5_knock_ct_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool database_base5_knock_ct_is_in_range(uint16_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool database_base5_knock_ct_is_in_phys_range(float value);

/**
 * Pack message BASE6.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int database_base6_pack(
    uint8_t *dst_p,
    const struct database_base6_t *src_p,
    size_t size);

/**
 * Unpack message BASE6.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int database_base6_unpack(
    struct database_base6_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from BASE6.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int database_base6_init(struct database_base6_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t database_base6_fuel_used_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float database_base6_fuel_used_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool database_base6_fuel_used_is_in_range(uint16_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool database_base6_fuel_used_is_in_phys_range(float value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t database_base6_fuel_flow_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float database_base6_fuel_flow_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool database_base6_fuel_flow_is_in_range(uint16_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool database_base6_fuel_flow_is_in_phys_range(float value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
int16_t database_base6_fuel_trim1_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float database_base6_fuel_trim1_decode(int16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool database_base6_fuel_trim1_is_in_range(int16_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool database_base6_fuel_trim1_is_in_phys_range(float value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
int16_t database_base6_fuel_trim2_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float database_base6_fuel_trim2_decode(int16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool database_base6_fuel_trim2_is_in_range(int16_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool database_base6_fuel_trim2_is_in_phys_range(float value);

/**
 * Pack message BASE7.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int database_base7_pack(
    uint8_t *dst_p,
    const struct database_base7_t *src_p,
    size_t size);

/**
 * Unpack message BASE7.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int database_base7_unpack(
    struct database_base7_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from BASE7.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int database_base7_init(struct database_base7_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t database_base7_lam1_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float database_base7_lam1_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool database_base7_lam1_is_in_range(uint16_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool database_base7_lam1_is_in_phys_range(float value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t database_base7_lam2_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float database_base7_lam2_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool database_base7_lam2_is_in_range(uint16_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool database_base7_lam2_is_in_phys_range(float value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t database_base7_fp_low_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float database_base7_fp_low_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool database_base7_fp_low_is_in_range(uint16_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool database_base7_fp_low_is_in_phys_range(float value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t database_base7_fp_high_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float database_base7_fp_high_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool database_base7_fp_high_is_in_range(uint16_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool database_base7_fp_high_is_in_phys_range(float value);

/**
 * Pack message BASE8.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int database_base8_pack(
    uint8_t *dst_p,
    const struct database_base8_t *src_p,
    size_t size);

/**
 * Unpack message BASE8.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int database_base8_unpack(
    struct database_base8_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from BASE8.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int database_base8_init(struct database_base8_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
int8_t database_base8_cam1_i_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float database_base8_cam1_i_decode(int8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool database_base8_cam1_i_is_in_range(int8_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool database_base8_cam1_i_is_in_phys_range(float value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
int8_t database_base8_cam1_itar_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float database_base8_cam1_itar_decode(int8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool database_base8_cam1_itar_is_in_range(int8_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool database_base8_cam1_itar_is_in_phys_range(float value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
int8_t database_base8_cam1_e_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float database_base8_cam1_e_decode(int8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool database_base8_cam1_e_is_in_range(int8_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool database_base8_cam1_e_is_in_phys_range(float value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
int8_t database_base8_cam1_etar_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float database_base8_cam1_etar_decode(int8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool database_base8_cam1_etar_is_in_range(int8_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool database_base8_cam1_etar_is_in_phys_range(float value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
int8_t database_base8_cam2_i_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float database_base8_cam2_i_decode(int8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool database_base8_cam2_i_is_in_range(int8_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool database_base8_cam2_i_is_in_phys_range(float value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
int8_t database_base8_cam2_itar_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float database_base8_cam2_itar_decode(int8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool database_base8_cam2_itar_is_in_range(int8_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool database_base8_cam2_itar_is_in_phys_range(float value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
int8_t database_base8_cam2_e_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float database_base8_cam2_e_decode(int8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool database_base8_cam2_e_is_in_range(int8_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool database_base8_cam2_e_is_in_phys_range(float value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
int8_t database_base8_cam2_etar_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float database_base8_cam2_etar_decode(int8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool database_base8_cam2_etar_is_in_range(int8_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool database_base8_cam2_etar_is_in_phys_range(float value);

/**
 * Pack message BASE9.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int database_base9_pack(
    uint8_t *dst_p,
    const struct database_base9_t *src_p,
    size_t size);

/**
 * Unpack message BASE9.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int database_base9_unpack(
    struct database_base9_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from BASE9.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int database_base9_init(struct database_base9_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t database_base9_egt1_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float database_base9_egt1_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool database_base9_egt1_is_in_range(uint8_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool database_base9_egt1_is_in_phys_range(float value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t database_base9_egt2_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float database_base9_egt2_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool database_base9_egt2_is_in_range(uint8_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool database_base9_egt2_is_in_phys_range(float value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t database_base9_egt3_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float database_base9_egt3_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool database_base9_egt3_is_in_range(uint8_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool database_base9_egt3_is_in_phys_range(float value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t database_base9_egt4_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float database_base9_egt4_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool database_base9_egt4_is_in_range(uint8_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool database_base9_egt4_is_in_phys_range(float value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t database_base9_egt5_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float database_base9_egt5_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool database_base9_egt5_is_in_range(uint8_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool database_base9_egt5_is_in_phys_range(float value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t database_base9_egt6_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float database_base9_egt6_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool database_base9_egt6_is_in_range(uint8_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool database_base9_egt6_is_in_phys_range(float value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t database_base9_egt7_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float database_base9_egt7_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool database_base9_egt7_is_in_range(uint8_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool database_base9_egt7_is_in_phys_range(float value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t database_base9_egt8_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float database_base9_egt8_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool database_base9_egt8_is_in_range(uint8_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool database_base9_egt8_is_in_phys_range(float value);

/**
 * Pack message BASE10.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int database_base10_pack(
    uint8_t *dst_p,
    const struct database_base10_t *src_p,
    size_t size);

/**
 * Unpack message BASE10.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int database_base10_unpack(
    struct database_base10_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from BASE10.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int database_base10_init(struct database_base10_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
int8_t database_base10_knock0_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float database_base10_knock0_decode(int8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool database_base10_knock0_is_in_range(int8_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool database_base10_knock0_is_in_phys_range(float value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
int8_t database_base10_knock1_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float database_base10_knock1_decode(int8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool database_base10_knock1_is_in_range(int8_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool database_base10_knock1_is_in_phys_range(float value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
int8_t database_base10_knock2_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float database_base10_knock2_decode(int8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool database_base10_knock2_is_in_range(int8_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool database_base10_knock2_is_in_phys_range(float value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
int8_t database_base10_knock3_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float database_base10_knock3_decode(int8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool database_base10_knock3_is_in_range(int8_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool database_base10_knock3_is_in_phys_range(float value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
int8_t database_base10_knock4_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float database_base10_knock4_decode(int8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool database_base10_knock4_is_in_range(int8_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool database_base10_knock4_is_in_phys_range(float value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
int8_t database_base10_knock5_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float database_base10_knock5_decode(int8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool database_base10_knock5_is_in_range(int8_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool database_base10_knock5_is_in_phys_range(float value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
int8_t database_base10_knock6_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float database_base10_knock6_decode(int8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool database_base10_knock6_is_in_range(int8_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool database_base10_knock6_is_in_phys_range(float value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
int8_t database_base10_knock7_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float database_base10_knock7_decode(int8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool database_base10_knock7_is_in_range(int8_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool database_base10_knock7_is_in_phys_range(float value);

/**
 * Pack message BASE11.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int database_base11_pack(
    uint8_t *dst_p,
    const struct database_base11_t *src_p,
    size_t size);

/**
 * Unpack message BASE11.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int database_base11_unpack(
    struct database_base11_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from BASE11.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int database_base11_init(struct database_base11_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t database_base11_brake_pedal_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float database_base11_brake_pedal_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool database_base11_brake_pedal_is_in_range(uint8_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool database_base11_brake_pedal_is_in_phys_range(float value);


#ifdef __cplusplus
}
#endif

#endif
